create DATABASE hims;

use hims;

CREATE TABLE visit_type(
   visit_type_id INT PRIMARY KEY auto_increment,
   visit_type VARCHAR(255) not null
);
insert into visit_type values (1, "Out Patient") , (2, "In Patient"), (3, "Emergency"), (4, "Day Care");

CREATE TABLE states(
	state_id INT PRIMARY KEY auto_increment,
    state_name  VARCHAR(255)
);

insert into states (state_name) values ("ANDAMAN AND NICOBAR ISLANDS"), ("ANDHRA PRADESH"),
("ARUNACHAL PRADESH"),
("ASSAM"),
("BIHAR"),
("CHHATTISGARH"),
("CHANDIGARH"),
("DAMAN AND DIU"),
("DELHI"),
("DADRA AND NAGAR HAVELI"),
("GOA"),
("GUJARAT"),
("HIMACHAL PRADESH"),
("HARYANA"),
("JAMMU AND KASHMIR"),
("JHARKHAND"),
("KERALA"),
("KARNATAKA"),
("LAKSHADWEEP"),
("MEGHALAYA"),
("MAHARASHTRA"),
("MANIPUR"),
("MADHYA PRADESH"),
("MIZORAM"),
("NAGALAND"),
("ORISSA"),
("PUNJAB"),
("PONDICHERRY"),
("RAJASTHAN"),
("SIKKIM"),
("TAMIL NADU"),
("TRIPURA"),
("TELANGANA"),
("UTTARAKHAND"),
("UTTAR PRADESH"),
("WEST BENGAL"),
("ODIS"), ("NA");

CREATE TABLE cities(
	city_id INT PRIMARY KEY auto_increment,
    city_name  VARCHAR(255),
    state_id int not null,
    FOREIGN KEY (state_id) REFERENCES states(state_id)
);
INSERT INTO cities (city_name, state_id) values  
("Mumbai",21),
("Delhi",9),
("Bengaluru",18),
("Ahmedabad",12),
("Hyderabad",33),
("Chennai",31),
("Kolkata",36),
("Pune",21),
("Jaipur",29),
("Surat",12),
("Lucknow",35),
("Kanpur",35),
("Nagpur",21),
("Patna",5),
("Indore",23),
("Thane",21),
("Bhopal",23),
("Visakhapatnam",2),
("Vadodara",12),
("Firozabad",35),
("Ludhiana",27),
("Rajkot",12),
("Agra",35),
("Siliguri",36),
("Nashik",21),
("Faridabad",14),
("Patiala",27),
("Meerut",35),
("Kalyan-Dombivali",21),
("Vasai-Virar",21),
("Varanasi",35),
("Srinagar",15),
("Dhanbad",16),
("Jodhpur",29),
("Amritsar",27),
("Raipur",6),
("Allahabad",35),
("Coimbatore",31),
("Jabalpur",23),
("Gwalior",23),
("Vijayawada",2),
("Madurai",31),
("Guwahati",4),
("Chandigarh",7),
("Hubli-Dharwad",18),
("Amroha",35),
("Moradabad",35),
("Gurgaon",14),
("Aligarh",35),
("Solapur",21),
("Ranchi",16),
("Jalandhar",27),
("Tiruchirappalli",31),
("Bhubaneswar",37),
("Salem",31),
("Warangal",33),
("Mira-Bhayandar",21),
("Thiruvananthapuram",17),
("Bhiwandi",21),
("Saharanpur",35),
("Guntur",2),
("Amravati",21),
("Bikaner",29),
("Noida",35),
("Jamshedpur",16),
("Bhilai Nagar",6),
("Cuttack",37),
("Kochi",17),
("Udaipur",29),
("Bhavnagar",12),
("Dehradun",34),
("Asansol",36),
("Nanded-Waghala",21),
("Ajmer",29),
("Jamnagar",12),
("Ujjain",23),
("Sangli",21),
("Loni",35),
("Jhansi",35),
("Pondicherry",0),
("Nellore",2),
("Jammu",15),
("Belagavi",18),
("Raurkela",37),
("Mangaluru",18),
("Tirunelveli",31),
("Malegaon",21),
("Gaya",5),
("Tiruppur",31),
("Davanagere",18),
("Kozhikode",17),
("Akola",21),
("Kurnool",2),
("Bokaro Steel City",16),
("Rajahmundry",2),
("Ballari",18),
("Agartala",32),
("Bhagalpur",5),
("Latur",21),
("Dhule",21),
("Korba",6),
("Bhilwara",29),
("Brahmapur",37),
("Mysore",0),
("Muzaffarpur",5),
("Kollam",17),
("Raghunathganj",36),
("Bilaspur",6),
("Shahjahanpur",35),
("Thrissur",17),
("Alwar",29),
("Kakinada",2),
("Nizamabad",33),
("Sagar",23),
("Tumkur",18),
("Hisar",14),
("Rohtak",14),
("Panipat",14),
("Darbhanga",5),
("Kharagpur",36),
("Aizawl",24),
("Ichalkaranji",21),
("Tirupati",2),
("Karnal",14),
("Bathinda",27),
("Rampur",35),
("Shivamogga",18),
("Ratlam",23),
("Modinagar",35),
("Durg",6),
("Shillong",20),
("Imphal",22),
("Hapur",35),
("Ranipet",31),
("Anantapur",2),
("Arrah",5),
("Karimnagar",33),
("Parbhani",21),
("Etawah",35),
("Bharatpur",29),
("Begusarai",5),
("New Delhi",9),
("Chhapra",5),
("Kadapa",2),
("Ramagundam",33),
("Pali",29),
("Satna",23),
("Vizianagaram",2),
("Katihar",5),
("Hardwar",34),
("Sonipat",14),
("Nagercoil",31),
("Thanjavur",31),
("Murwara (Katni)",23),
("Naihati",36),
("Sambhal",35),
("Nadiad",12),
("Yamunanagar",14),
("English Bazar",36),
("Eluru",2),
("Munger",5),
("Panchkula",14),
("Raayachuru",18),
("Panvel",21),
("Deoghar",16),
("Ongole",2),
("Nandyal",2),
("Morena",23),
("Bhiwani",14),
("Porbandar",12),
("Palakkad",17),
("Anand",12),
("Purnia",5),
("Baharampur",36),
("Barmer",29),
("Morvi",12),
("Orai",35),
("Bahraich",35),
("Sikar",29),
("Vellore",31),
("Singrauli",23),
("Khammam",33),
("Mahesana",12),
("Silchar",4),
("Sambalpur",37),
("Rewa",23),
("Unnao",35),
("Hugli-Chinsurah",36),
("Raiganj",36),
("Phusro",16),
("Adityapur",16),
("Alappuzha",17),
("Bahadurgarh",14),
("Machilipatnam",2),
("Rae Bareli",35),
("Jalpaiguri",36),
("Bharuch",12),
("Pathankot",27),
("Hoshiarpur",27),
("Baramula",15),
("Adoni",2),
("Jind",14),
("Tonk",29),
("Tenali",2),
("Kancheepuram",31),
("Vapi",12),
("Sirsa",14),
("Navsari",12),
("Mahbubnagar",33),
("Puri",37),
("Robertson Pet",18),
("Erode",31),
("Batala",27),
("Haldwani-cum-Kathgodam",34),
("Vidisha",23),
("Saharsa",5),
("Thanesar",14),
("Chittoor",2),
("Veraval",12),
("Lakhimpur",35),
("Sitapur",35),
("Hindupur",2),
("Santipur",36),
("Balurghat",36),
("Ganjbasoda",23),
("Moga",27),
("Proddatur",2),
("Srinagar",34),
("Medinipur",36),
("Habra",36),
("Sasaram",5),
("Hajipur",5),
("Bhuj",12),
("Shivpuri",23),
("Ranaghat",36),
("Shimla",13),
("Tiruvannamalai",31),
("Kaithal",14),
("Rajnandgaon",6),
("Godhra",12),
("Hazaribag",16),
("Bhimavaram",2),
("Mandsaur",23),
("Dibrugarh",4),
("Kolar",18),
("Bankura",36),
("Mandya",18),
("Dehri-on-Sone",5),
("Madanapalle",2),
("Malerkotla",27),
("Lalitpur",35),
("Bettiah",5),
("Pollachi",31),
("Khanna",27),
("Neemuch",23),
("Palwal",14),
("Palanpur",12),
("Guntakal",2),
("Nabadwip",36),
("Udupi",18),
("Jagdalpur",6),
("Motihari",5),
("Pilibhit",35),
("Dimapur",25),
("Mohali",27),
("Sadulpur",29),
("Rajapalayam",31),
("Dharmavaram",2),
("Kashipur",34),
("Sivakasi",31),
("Darjiling",36),
("Chikkamagaluru",18),
("Gudivada",2),
("Baleshwar Town",37),
("Mancherial",33),
("Srikakulam",2),
("Adilabad",33),
("Yavatmal",21),
("Barnala",27),
("Nagaon",4),
("Narasaraopet",2),
("Raigarh",6),
("Roorkee",34),
("Valsad",12),
("Ambikapur",6),
("Giridih",16),
("Chandausi",35),
("Purulia",36),
("Patan",12),
("Bagaha",5),
("Hardoi",35),
("Achalpur",21),
("Osmanabad",21),
("Deesa",12),
("Nandurbar",21),
("Azamgarh",35),
("Ramgarh",16),
("Firozpur",27),
("Baripada Town",37),
("Karwar",18),
("Siwan",5),
("Rajampet",2),
("Pudukkottai",31),
("Anantnag",15),
("Tadpatri",2),
("Satara",21),
("Bhadrak",37),
("Kishanganj",5),
("Suryapet",33),
("Wardha",21),
("Ranebennuru",18),
("Amreli",12),
("Neyveli (TS)",31),
("Jamalpur",5),
("Marmagao",11),
("Udgir",21),
("Tadepalligudem",2),
("Nagapattinam",31),
("Buxar",5),
("Aurangabad",21),
("Jehanabad",5),
("Phagwara",27),
("Khair",35),
("Sawai Madhopur",29),
("Kapurthala",27),
("Chilakaluripet",2),
("Aurangabad",5),
("Malappuram",17),
("Rewari",14),
("Nagaur",29),
("Sultanpur",35),
("Nagda",23),
("Port Blair",1),
("Lakhisarai",5),
("Panaji",11),
("Tinsukia",4),
("Itarsi",23),
("Kohima",25),
("Balangir",37),
("Nawada",5),
("Jharsuguda",37),
("Jagtial",33),
("Viluppuram",31),
("Amalner",21),
("Zirakpur",27),
("Tanda",35),
("Tiruchengode",31),
("Nagina",35),
("Yemmiganur",2),
("Vaniyambadi",31),
("Sarni",23),
("Theni Allinagaram",31),
("Margao",11),
("Akot",21),
("Sehore",23),
("Mhow Cantonment",23),
("Kot Kapura",27),
("Makrana",29),
("Pandharpur",21),
("Miryalaguda",33),
("Shamli",35),
("Seoni",23),
("Ranibennur",18),
("Kadiri",2),
("Shrirampur",21),
("Rudrapur",34),
("Parli",21),
("Najibabad",35),
("Nirmal",33),
("Udhagamandalam",31),
("Shikohabad",35),
("Jhumri Tilaiya",16),
("Aruppukkottai",31),
("Ponnani",17),
("Jamui",5),
("Sitamarhi",5),
("Chirala",2),
("Anjar",12),
("Karaikal",0),
("Hansi",14),
("Anakapalle",2),
("Mahasamund",6),
("Faridkot",27),
("Saunda",16),
("Dhoraji",12),
("Paramakudi",31),
("Balaghat",23),
("Sujangarh",29),
("Khambhat",12),
("Muktsar",27),
("Rajpura",27),
("Kavali",2),
("Dhamtari",6),
("Ashok Nagar",23),
("Sardarshahar",29),
("Mahuva",12),
("Bargarh",37),
("Kamareddy",33),
("Sahibganj",16),
("Kothagudem",33),
("Ramanagaram",18),
("Gokak",18),
("Tikamgarh",23),
("Araria",5),
("Rishikesh",34),
("Shahdol",23),
("Medininagar (Daltonganj)",16),
("Arakkonam",31),
("Washim",21),
("Sangrur",27),
("Bodhan",33),
("Fazilka",27),
("Palacole",2),
("Keshod",12),
("Sullurpeta",2),
("Wadhwan",12),
("Gurdaspur",27),
("Vatakara",17),
("Tura",20),
("Narnaul",14),
("Kharar",27),
("Yadgir",18),
("Ambejogai",21),
("Ankleshwar",12),
("Savarkundla",12),
("Paradip",37),
("Virudhachalam",31),
("Kanhangad",17),
("Kadi",12),
("Srivilliputhur",31),
("Gobindgarh",27),
("Tindivanam",31),
("Mansa",27),
("Taliparamba",17),
("Manmad",21),
("Tanuku",2),
("Rayachoti",2),
("Virudhunagar",31),
("Koyilandy",17),
("Jorhat",4),
("Karur",31),
("Valparai",31),
("Srikalahasti",2),
("Neyyattinkara",17),
("Bapatla",2),
("Fatehabad",14),
("Malout",27),
("Sankarankovil",31),
("Tenkasi",31),
("Ratnagiri",21),
("Rabkavi Banhatti",18),
("Sikandrabad",35),
("Chaibasa",16),
("Chirmiri",6),
("Palwancha",33),
("Bhawanipatna",37),
("Kayamkulam",17),
("Pithampur",23),
("Nabha",27),
("Shahabad, Hardoi",35),
("Dhenkanal",37),
("Uran Islampur",21),
("Gopalganj",5),
("Bongaigaon City",4),
("Palani",31),
("Pusad",21),
("Sopore",15),
("Pilkhuwa",35),
("Tarn Taran",27),
("Renukoot",35),
("Mandamarri",33),
("Shahabad",18),
("Barbil",37),
("Koratla",33),
("Madhubani",5),
("Arambagh",36),
("Gohana",14),
("Ladnu",29),
("Pattukkottai",31),
("Sirsi",18),
("Sircilla",33),
("Tamluk",36),
("Jagraon",27),
("AlipurdUrban Agglomerationr",36),
("Alirajpur",23),
("Tandur",33),
("Naidupet",2),
("Tirupathur",31),
("Tohana",14),
("Ratangarh",29),
("Dhubri",4),
("Masaurhi",5),
("Visnagar",12),
("Vrindavan",35),
("Nokha",29),
("Nagari",2),
("Narwana",14),
("Ramanathapuram",31),
("Ujhani",35),
("Samastipur",5),
("Laharpur",35),
("Sangamner",21),
("Nimbahera",29),
("Siddipet",33),
("Suri",36),
("Diphu",4),
("Jhargram",36),
("Shirpur-Warwade",21),
("Tilhar",35),
("Sindhnur",18),
("Udumalaipettai",31),
("Malkapur",21),
("Wanaparthy",33),
("Gudur",2),
("Kendujhar",37),
("Mandla",23),
("Mandi",13),
("Nedumangad",17),
("North Lakhimpur",4),
("Vinukonda",2),
("Tiptur",18),
("Gobichettipalayam",31),
("Sunabeda",37),
("Wani",21),
("Upleta",12),
("Narasapuram",2),
("Nuzvid",2),
("Tezpur",4),
("Una",12),
("Markapur",2),
("Sheopur",23),
("Thiruvarur",31),
("Sidhpur",12),
("Sahaswan",35),
("Suratgarh",29),
("Shajapur",23),
("Rayagada",37),
("Lonavla",21),
("Ponnur",2),
("Kagaznagar",33),
("Gadwal",33),
("Bhatapara",6),
("Kandukur",2),
("Sangareddy",33),
("Unjha",12),
("Lunglei",24),
("Karimganj",4),
("Kannur",17),
("Bobbili",2),
("Mokameh",5),
("Talegaon Dabhade",21),
("Anjangaon",21),
("Mangrol",12),
("Sunam",27),
("Gangarampur",36),
("Thiruvallur",31),
("Tirur",17),
("Rath",35),
("Jatani",37),
("Viramgam",12),
("Rajsamand",29),
("Yanam",0),
("Kottayam",17),
("Panruti",31),
("Dhuri",27),
("Namakkal",31),
("Kasaragod",17),
("Modasa",12),
("Rayadurg",2),
("Supaul",5),
("Kunnamkulam",17),
("Umred",21),
("Bellampalle",33),
("Sibsagar",4),
("Mandi Dabwali",14),
("Ottappalam",17),
("Dumraon",5),
("Samalkot",2),
("Jaggaiahpet",2),
("Goalpara",4),
("Tuni",2),
("Lachhmangarh",29),
("Bhongir",33),
("Amalapuram",2),
("Firozpur Cantt.",27),
("Vikarabad",33),
("Thiruvalla",17),
("Sherkot",35),
("Palghar",21),
("Shegaon",21),
("Jangaon",33),
("Bheemunipatnam",2),
("Panna",23),
("Thodupuzha",17),
("KathUrban Agglomeration",15),
("Palitana",12),
("Arwal",5),
("Venkatagiri",2),
("Kalpi",35),
("Rajgarh (Churu)",29),
("Sattenapalle",2),
("Arsikere",18),
("Ozar",21),
("Thirumangalam",31),
("Petlad",12),
("Nasirabad",29),
("Phaltan",21),
("Rampurhat",36),
("Nanjangud",18),
("Forbesganj",5),
("Tundla",35),
("BhabUrban Agglomeration",5),
("Sagara",18),
("Pithapuram",2),
("Sira",18),
("Bhadrachalam",33),
("Charkhi Dadri",14),
("Chatra",16),
("Palasa Kasibugga",2),
("Nohar",29),
("Yevla",21),
("Sirhind Fatehgarh Sahib",27),
("Bhainsa",33),
("Parvathipuram",2),
("Shahade",21),
("Chalakudy",17),
("Narkatiaganj",5),
("Kapadvanj",12),
("Macherla",2),
("Raghogarh-Vijaypur",23),
("Rupnagar",27),
("Naugachhia",5),
("Sendhwa",23),
("Byasanagar",37),
("Sandila",35),
("Gooty",2),
("Salur",2),
("Nanpara",35),
("Sardhana",35),
("Vita",21),
("Gumia",16),
("Puttur",18),
("Jalandhar Cantt.",27),
("Nehtaur",35),
("Changanassery",17),
("Mandapeta",2),
("Dumka",16),
("Seohara",35),
("Umarkhed",21),
("Madhupur",16),
("Vikramasingapuram",31),
("Punalur",17),
("Kendrapara",37),
("Sihor",12),
("Nellikuppam",31),
("Samana",27),
("Warora",21),
("Nilambur",17),
("Rasipuram",31),
("Ramnagar",34),
("Jammalamadugu",2),
("Nawanshahr",27),
("Thoubal",22),
("Athni",18),
("Cherthala",17),
("Sidhi",23),
("Farooqnagar",33),
("Peddapuram",2),
("Chirkunda",16),
("Pachora",21),
("Madhepura",5),
("Pithoragarh",34),
("Tumsar",21),
("Phalodi",29),
("Tiruttani",31),
("Rampura Phul",27),
("Perinthalmanna",17),
("Padrauna",35),
("Pipariya",23),
("Dalli-Rajhara",6),
("Punganur",2),
("Mattannur",17),
("Mathura",35),
("Thakurdwara",35),
("Nandivaram-Guduvancheri",31),
("Mulbagal",18),
("Manjlegaon",21),
("Wankaner",12),
("Sillod",21),
("Nidadavole",2),
("Surapura",18),
("Rajagangapur",37),
("Sheikhpura",5),
("Parlakhemundi",37),
("Kalimpong",36),
("Siruguppa",18),
("Arvi",21),
("Limbdi",12),
("Barpeta",4),
("Manglaur",34),
("Repalle",2),
("Mudhol",18),
("Shujalpur",23),
("Mandvi",12),
("Thangadh",12),
("Sironj",23),
("Nandura",21),
("Shoranur",17),
("Nathdwara",29),
("Periyakulam",31),
("Sultanganj",5),
("Medak",33),
("Narayanpet",33),
("Raxaul Bazar",5),
("Rajauri",15),
("Pernampattu",31),
("Nainital",34),
("Ramachandrapuram",2),
("Vaijapur",21),
("Nangal",27),
("Sidlaghatta",18),
("Punch",15),
("Pandhurna",23),
("Wadgaon Road",21),
("Talcher",37),
("Varkala",17),
("Pilani",29),
("Nowgong",23),
("Naila Janjgir",6),
("Mapusa",11),
("Vellakoil",31),
("Merta City",29),
("Sivaganga",31),
("Mandideep",23),
("Sailu",21),
("Vyara",12),
("Kovvur",2),
("Vadalur",31),
("Nawabganj",35),
("Padra",12),
("Sainthia",36),
("Siana",35),
("Shahpur",18),
("Sojat",29),
("Noorpur",35),
("Paravoor",17),
("Murtijapur",21),
("Ramnagar",5),
("Sundargarh",37),
("Taki",36),
("Saundatti-Yellamma",18),
("Pathanamthitta",17),
("Wadi",18),
("Rameshwaram",31),
("Tasgaon",21),
("Sikandra Rao",35),
("Sihora",23),
("Tiruvethipuram",31),
("Tiruvuru",2),
("Mehkar",21),
("Peringathur",17),
("Perambalur",31),
("Manvi",18),
("Zunheboto",25),
("Mahnar Bazar",5),
("Attingal",17),
("Shahbad",14),
("Puranpur",35),
("Nelamangala",18),
("Nakodar",27),
("Lunawada",12),
("Murshidabad",36),
("Mahe",0),
("Lanka",4),
("Rudauli",35),
("Tuensang",25),
("Lakshmeshwar",18),
("Zira",27),
("Yawal",21),
("Thana Bhawan",35),
("Ramdurg",18),
("Pulgaon",21),
("Sadasivpet",33),
("Nargund",18),
("Neem-Ka-Thana",29),
("Memari",36),
("Nilanga",21),
("Naharlagun",3),
("Pakaur",16),
("Wai",21),
("Tarikere",18),
("Malavalli",18),
("Raisen",23),
("Lahar",23),
("Uravakonda",2),
("Savanur",18),
("Sirohi",29),
("Udhampur",15),
("Umarga",21),
("Pratapgarh",29),
("Lingsugur",18),
("Usilampatti",31),
("Palia Kalan",35),
("Wokha",25),
("Rajpipla",12),
("Vijayapura",18),
("Rawatbhata",29),
("Sangaria",29),
("Paithan",21),
("Rahuri",21),
("Patti",27),
("Zaidpur",35),
("Lalsot",29),
("Maihar",23),
("Vedaranyam",31),
("Nawapur",21),
("Solan",13),
("Vapi",12),
("Sanawad",23),
("Warisaliganj",5),
("Revelganj",5),
("Sabalgarh",23),
("Tuljapur",21),
("Simdega",16),
("Musabani",16),
("Kodungallur",17),
("Phulabani",37),
("Umreth",12),
("Narsipatnam",2),
("Nautanwa",35),
("Rajgir",5),
("Yellandu",33),
("Sathyamangalam",31),
("Pilibanga",29),
("Morshi",21),
("Pehowa",14),
("Sonepur",5),
("Pappinisseri",17),
("Zamania",35),
("Mihijam",16),
("Purna",21),
("Puliyankudi",31),
("Umaria",23),
("Porsa",23),
("Naugawan Sadat",35),
("Fatehpur Sikri",35),
("Manuguru",33),
("Udaipur",32),
("Pipar City",29),
("Pattamundai",37),
("Nanjikottai",31),
("Taranagar",29),
("Yerraguntla",2),
("Satana",21),
("Sherghati",5),
("Sankeshwara",18),
("Madikeri",18),
("Thuraiyur",31),
("Sanand",12),
("Rajula",12),
("Kyathampalle",33),
("Shahabad, Rampur",35),
("Tilda Newra",6),
("Narsinghgarh",23),
("Chittur-Thathamangalam",17),
("Malaj Khand",23),
("Sarangpur",23),
("Robertsganj",35),
("Sirkali",31),
("Radhanpur",12),
("Tiruchendur",31),
("Utraula",35),
("Patratu",16),
("Vijainagar, Ajmer",29),
("Periyasemur",31),
("Pathri",21),
("Sadabad",35),
("Talikota",18),
("Sinnar",21),
("Mungeli",6),
("Sedam",18),
("Shikaripur",18),
("Sumerpur",29),
("Sattur",31),
("Sugauli",5),
("Lumding",4),
("Vandavasi",31),
("Titlagarh",37),
("Uchgaon",21),
("Mokokchung",25),
("Paschim Punropara",36),
("Sagwara",29),
("Ramganj Mandi",29),
("Tarakeswar",36),
("Mahalingapura",18),
("Dharmanagar",32),
("Mahemdabad",12),
("Manendragarh",6),
("Uran",21),
("Tharamangalam",31),
("Tirukkoyilur",31),
("Pen",21),
("Makhdumpur",5),
("Maner",5),
("Oddanchatram",31),
("Palladam",31),
("Mundi",23),
("Nabarangapur",37),
("Mudalagi",18),
("Samalkha",14),
("Nepanagar",23),
("Karjat",21),
("Ranavav",12),
("Pedana",2),
("Pinjore",14),
("Lakheri",29),
("Pasan",23),
("Puttur",2),
("Vadakkuvalliyur",31),
("Tirukalukundram",31),
("Mahidpur",23),
("Mussoorie",34),
("Muvattupuzha",17),
("Rasra",35),
("Udaipurwati",29),
("Manwath",21),
("Adoor",17),
("Uthamapalayam",31),
("Partur",21),
("Nahan",13),
("Ladwa",14),
("Mankachar",4),
("Nongstoin",20),
("Losal",29),
("Sri Madhopur",29),
("Ramngarh",29),
("Mavelikkara",17),
("Rawatsar",29),
("Rajakhera",29),
("Lar",35),
("Lal Gopalganj Nindaura",35),
("Muddebihal",18),
("Sirsaganj",35),
("Shahpura",29),
("Surandai",31),
("Sangole",21),
("Pavagada",18),
("Tharad",12),
("Mansa",12),
("Umbergaon",12),
("Mavoor",17),
("Nalbari",4),
("Talaja",12),
("Malur",18),
("Mangrulpir",21),
("Soro",37),
("Shahpura",29),
("Vadnagar",12),
("Raisinghnagar",29),
("Sindhagi",18),
("Sanduru",18),
("Sohna",14),
("Manavadar",12),
("Pihani",35),
("Safidon",14),
("Risod",21),
("Rosera",5),
("Sankari",31),
("Malpura",29),
("Sonamukhi",36),
("Shamsabad, Agra",35),
("Nokha",5),
("PandUrban Agglomeration",36),
("Mainaguri",36),
("Afzalpur",18),
("Shirur",21),
("Salaya",12),
("Shenkottai",31),
("Pratapgarh",32),
("Vadipatti",31),
("Nagarkurnool",33),
("Savner",21),
("Sasvad",21),
("Rudrapur",35),
("Soron",35),
("Sholingur",31),
("Pandharkaoda",21),
("Perumbavoor",17),
("Maddur",18),
("Nadbai",29),
("Talode",21),
("Shrigonda",21),
("Madhugiri",18),
("Tekkalakote",18),
("Seoni-Malwa",23),
("Shirdi",21),
("SUrban Agglomerationr",35),
("Terdal",18),
("Raver",21),
("Tirupathur",31),
("Taraori",14),
("Mukhed",21),
("Manachanallur",31),
("Rehli",23),
("Sanchore",29),
("Rajura",21),
("Piro",5),
("Mudabidri",18),
("Vadgaon Kasba",21),
("Nagar",29),
("Vijapur",12),
("Viswanatham",31),
("Polur",31),
("Panagudi",31),
("Manawar",23),
("Tehri",34),
("Samdhan",35),
("Pardi",12),
("Rahatgarh",23),
("Panagar",23),
("Uthiramerur",31),
("Tirora",21),
("Rangia",4),
("Sahjanwa",35),
("Magadi",18),
("Rajgarh (Alwar)",29),
("Rafiganj",5),
("Tarana",23),
("Rampur Maniharan",35),
("Sheoganj",29),
("Raikot",27),
("Pauri",34),
("Sumerpur",35),
("Navalgund",18),
("Shahganj",35),
("Marhaura",5),
("Tulsipur",35),
("Sadri",29),
("Thiruthuraipoondi",31),
("Shiggaon",18),
("Pallapatti",31),
("Mahendragarh",14),
("Sausar",23),
("Ponneri",31),
("Mahad",21),
("Lohardaga",16),
("Tirwaganj",35),
("Margherita",4),
("Sundarnagar",13),
("Rajgarh",23),
("Mangaldoi",4),
("Renigunta",2),
("Longowal",27),
("Ratia",14),
("Lalgudi",31),
("Shrirangapattana",18),
("Niwari",23),
("Natham",31),
("Unnamalaikadai",31),
("PurqUrban Agglomerationzi",35),
("Shamsabad, Farrukhabad",35),
("Mirganj",5),
("Todaraisingh",29),
("Warhapur",35),
("Rajam",2),
("Urmar Tanda",27),
("Lonar",21),
("Powayan",35),
("P.N.Patti",31),
("Palampur",13),
("Srisailam Project (Right Flank Colony) Township",2),
("Sindagi",18),
("Sandi",35),
("Vaikom",17),
("Malda",36),
("Tharangambadi",31),
("Sakaleshapura",18),
("Lalganj",5),
("Malkangiri",37),
("Rapar",12),
("Mauganj",23),
("Todabhim",29),
("Srinivaspur",18),
("Murliganj",5),
("Reengus",29),
("Sawantwadi",21),
("Tittakudi",31),
("Lilong",22),
("Rajaldesar",29),
("Pathardi",21),
("Achhnera",35),
("Pacode",31),
("Naraura",35),
("Nakur",35),
("Palai",17),
("Morinda, India",27),
("Manasa",23),
("Nainpur",23),
("Sahaspur",35),
("Pauni",21),
("Prithvipur",23),
("Ramtek",21),
("Silapathar",4),
("Songadh",12),
("Safipur",35),
("Sohagpur",23),
("Mul",21),
("Sadulshahar",29),
("Phillaur",27),
("Sambhar",29),
("Prantij",29),
("Nagla",34),
("Pattran",27),
("Mount Abu",29),
("Reoti",35),
("Tenu dam-cum-Kathhara",16),
("Panchla",36),
("Sitarganj",34),
("Pasighat",3),
("Motipur",5),
("O\" Valley",31),
("Raghunathpur",36),
("Suriyampalayam",31),
("Qadian",27),
("Rairangpur",37),
("Silvassa",10),
("Nowrozabad (Khodargama)",23),
("Mangrol",29),
("Soyagaon",21),
("Sujanpur",27),
("Manihari",5),
("Sikanderpur",35),
("Mangalvedhe",21),
("Phulera",29),
("Ron",18),
("Sholavandan",31),
("Saidpur",35),
("Shamgarh",23),
("Thammampatti",31),
("Maharajpur",23),
("Multai",23),
("Mukerian",27),
("Sirsi",35),
("Purwa",35),
("Sheohar",5),
("Namagiripettai",31),
("Parasi",35),
("Lathi",12),
("Lalganj",35),
("Narkhed",21),
("Mathabhanga",36),
("Shendurjana",21),
("Peravurani",31),
("Mariani",4),
("Phulpur",35),
("Rania",14),
("Pali",23),
("Pachore",23),
("Parangipettai",31),
("Pudupattinam",31),
("Panniyannur",17),
("Maharajganj",5),
("Rau",23),
("Monoharpur",36),
("Mandawa",29),
("Marigaon",4),
("Pallikonda",31),
("Pindwara",29),
("Shishgarh",35),
("Patur",21),
("Mayang Imphal",22),
("Mhowgaon",23),
("Guruvayoor",17),
("Mhaswad",21),
("Sahawar",35),
("Sivagiri",31),
("Mundargi",18),
("Punjaipugalur",31),
("Kailasahar",32),
("Samthar",35),
("Sakti",6),
("Sadalagi",18),
("Silao",5),
("Mandalgarh",29),
("Loha",21),
("Pukhrayan",35),
("Padmanabhapuram",31),
("Belonia",32),
("Saiha",24),
("Srirampore",36),
("Talwara",27),
("Puthuppally",17),
("Khowai",32),
("Vijaypur",23),
("Takhatgarh",29),
("Thirupuvanam",31),
("Adra",36),
("Piriyapatna",18),
("Obra",35),
("Adalaj",12),
("Nandgaon",21),
("Barh",5),
("Chhapra",12),
("Panamattom",17),
("Niwai",35),
("Bageshwar",34),
("Tarbha",37),
("Adyar",18),
("Narsinghgarh",23),
("Warud",21),
("Asarganj",5),
("Sarsod",14),
("Navi Mumbai",21),
("Goa",11),
("Bhilai",6),
("Midnandhra pradeshore",36),
("Ballia",35),
("Jaunpur",35),
("Faizabad",35),
("Ballia",35),
("Akbarpur",35),
("Amangang",23),
("Vizag",2),
("Barpali",37),
("Calicut",17),
("Dimandhra pradeshur",25),
("Cooch Behar",36),
("Jammu jk",15),
("BALRAmadhya pradeshUR",35),
("Beed",21),
("Shantipur",36),
("Basti",35),
("Pratandhra pradeshgarh",35),
("Katwa",36),
("Guna",23),
("Durgandhra pradeshur 2",36),
("Kalchini",36),
("Khargone",23),
("Krishnanagar",36),
("Kalna",36),
("Kayakuchi",4),
("Patiala - Patiala",27),
("Parasia Chhindwara",23),
("LAKHImadhya pradeshUR",35),
("Mavelikara",17),
("Burdwan",36),
("North Lakhimadhya pradeshur",4),
("Dalsingsarai",5),
("Basirhat",36),
("Jaswantnagar",35),
("Haridwar",34),
("Abohar",27),
("Tiruvalla",17),
("Barama",4),
("Tirupathi",2),
("Chhindwara",9),
("Belari",18),
("Nawalgarh",29),
("Mau",35),
("Mandsour",23),
("Gonda",35),
("Jaunpur",35),
("Nanded",21),
("Durgandhra pradeshur",36),
("Jammikunta",33),
("Jalna",21),
("Faizabad",35),
("Mirzandhra pradeshur",35),
("Katni",23),
("Sarupeta",4),
("Pratandhra pradeshgarh",29),
("Sivasagar",4),
("Almora",34),
("Mysuru",18),
("Gurugram",14),
("Sonari",16),
("Jalgaon",21),
("Panskura",36),
("Barnaddi",4),
("Khargone",23),
("Chhatarpur",23),
("Rethi",21),
("Dhokuakhana",4),
("Krishnanagar",9),
("Barhi",23),
("Bokajan",25),
("Machhali Shahar",35),
("Chhindwara",23),
("Petlawad",23),
("Ferozepur",27),
("Ghumarwin",13),
("Bihpuria",4),
("Akbarpur",35),
("Durgandhra pradeshur 1",36),
("Sindkhed Raja",21),
("Buldana",21),
("Bolpur",36),
("Ghazipur",35),
("Rajpur/barion",6),
("Rudrandhra pradeshur",34),
("Mangalore",18),
("Seramadhya pradeshore",36),
("Uttarpara",36),
("Kherri chamba",13),
("Trivandrum",17),
("Rethare",21),
("Vasco Da Gama",21),
("Chamba",13),
("Khatima",34),
("Karad",21),
("AMBIKandhra pradeshUR",6),
("Bayana",29),
("Pondi",31),
("Chandannagar",36),
("Machalpur",23),
("Gorakhpur",35),
("Visakhandhra pradeshatnam",2),
("Howrah",36),
("Dholpur",29),
("Mamdot",27),
("Solandhra pradeshur",21),
("Jirandhra pradeshur",23),
("Trichy",31),
("Kadandhra pradesha",2),
("Gorkhandhra pradeshur",35),
("Ernakulam",17),
("Chamadhya pradeshavat",34),
("Balramadhya pradeshur",35),
("Gondia",21),
("Etah",35),
("Kota",29),
("Ramanagara",18),
("Prayagraj",35),
("Berhamadhya pradeshur",37),
("Basti",35),
("Villupuram",31),
("Rajgangpur",37),
("Patran",27),
("Biaora",23),
("Dindigul",31),
("Gazipur",35),
("Farrukhabad",35),
("Khilchipur",23),
("Kalamb",21),
("Bhatgaon",6),
("Shivmogga",18),
("banandhra pradeshura",23),
("Nagrota Bagwan",13),
("Darwha",21),
("Chandhra pradeshiheda",23),
("Chhatarpur",9),
("Vizag",2),
("Rudrandhra pradeshur",34),
("Dewas",23),
("Lakhanpur",15),
("Gangtok",30),
("Khamgaon",21),
("Berhamadhya pradeshur",37),
("Hamirpur",13),
("Khujner",23),
("Jhunjhunu",29),
("Ghazipur",35),
("Gorakhpur",35),
("Pithauraghar",34),
("Haridwar",34),
("Surajpur",6),
("Bolpur",2),
("Rourkela",37),
("Bishramadhya pradeshur",34),
("Angul",37),
("Bardhaman",36),
("Chhatarpur",23),
("Chhindwara",23),
("Wayanad",21),
("Karaikudi",31),
("Brahmandhra pradeshur",37),
("Barasat",36),
("Jaubpur",35),
("Jaunpur",35),
("Kothamangalam",17),
("Khilchipur",23),
("Kadegaon",21),
("Doiwala",34),
("Angamaly",17),
("Tandhra pradesha",2),
("Kasegaon",21),
("Banda",35),
("Fatehgarh",35),
("Talen",23),
("Dharmshala",13),
("Cochin",17),
("Jirandhra pradeshur",23),
("Biswanath Chariali",4),
("Bongaigaon",4),
("Roing",3),
("Dhekiajuli",4),
("Balramadhya pradeshur",35),
("Bhinay",29),
("Kadamtala",36),
("Udalguri",4),
("Sonitpur",4),
("Raebareli",35),
("Nanubazar",36),
("kanchanpur",32),
("Patori",5),
("Bishagarh",32),
("Panisagar",32),
("Jirania",32),
("Umariya",23),
("Sabroom",32),
("Lalburra",2),
("Kokrajhar",4),
("Kalyanpur",5),
("Bulandshahr",35),
("Subroom",32),
("Bajpur",34),
("Gohpur",4),
("Melaghar",32),
("Topdara",29),
("Nagra",29),
("Shantirbazar",4),
("Adarsh Nagar",35),
("Hatta",21),
("Kesar Ganj",35),
("Baikhora",32),
("Abu Road",29),
("Raebareli",35),
("Banda",35),
("Digboi",4),
("Balaramadhya pradeshur",35),
("Damoh",23),
("Kaimganj",35),
("Santhaldih",36),
("Belda",36),
("Katni",23),
("Arjuni Morgaon",21),
("Potashpur",36),
("Akole",21),
("Jhalida",36),
("Banda",9),
("Srijangram",4),
("Sindri",16),
("Barabazar",36),
("Bengtal",4),
("Sitandhra pradeshur",35),
("Bijni",4),
("Contai",36),
("Sorbhog",4),
("Tirupur",31),
("Jahalda",36),
("Egra",36),
("Santhaldih",36),
("Kotshila",36),
("Jhabua",23),
("Anara",36),
("Umariya",23),
("Pauri Garhwal",34),
("Jhalda",36),
("Banda",35),
("Arsha",36),
("Chembur Mumbai",21),
("Chandiya",23),
("Kustaur",36),
("Jahalda",33),
("Dubra",36),
("Ballia",35),
("Lalburra",23),
("Dharamkot",27),
("Nawalgarh",9),
("Ashok",21),
("Gourangdih",36),
("Paniparul",36),
("Bagalkot",18),
("Shamsabad",35),
("Waraseoni",23),
("Hatta",12),
("Thindivanam",31),
("Howly",4),
("Ruderpur",34),
("Borivali",21),
("Belgaum",18),
("Baroda",12),
("Midnandhra pradeshore",33),
("Ghograndhra pradeshar",4),
("Mairang",20),
("Ratlan",23),
("Kopaganj",35),
("Gugamukh",4),
("Aluva",17),
("Ramnad",31),
("North Lakhimadhya pradeshur",35),
("Berhamadhya pradeshur, WB",36),
("Belgaum",35),
("Mulund",21),
("Dinandhra pradeshur",25),
("Falakata",36),
("Nazira",4),
("Bharthna",35),
("Nandakumar",36),
("Mecheda",36),
("Moyna",36),
("Laluk",4),
("Abhaypur",35),
("Sonari",4),
("Santacruz",21),
("Bamniya",23),
("Hosangabad",23),
("Mukalmua",4),
("Umshing",20),
("Dimandhra pradeshyr",25),
("Jammu jk",15),
("Dabaliyandhra pradeshara",4),
("Khetiya",23),
("Various",21),
("Harda",23),
("Pratandhra pradeshgarh",35),
("Jowai",36),
("Hanamkonda",33),
("Chakdah",36),
("Badkulla",36),
("Katangi",23),
("Hathras",35),
("Ottandhra pradeshalam",17),
("Raypuriya",29),
("Wakad",21),
("Berhamadhya pradeshur",36),
("East Delhi",9),
("Dataganj",35),
("Jowai",20),
("Bhawanipur",35),
("Jaora",23),
("Shahnagar",23),
("Ghaziabad",35),
("Tajpur",36),
("Ladrymbai",20),
("Barhi",16),
("Garoth",23),
("Dhariwal",27),
("Gogawa",23),
("Kalyani",36),
("Mavelikeara",17),
("Barobisha",36),
("Pawai",21),
("Birnagar",36),
("Haldwani",34),
("Odisha",37),
("Latwa",35),
("Yeola",21),
("Pratandhra pradeshgarh",2),
("Kandiwali",21),
("Bijnor",35),
("Meghnagar",23),
("Bathari",13),
("Jain medical hall st",6),
("Mirzapur",35),
("Durgapur",36),
("Midnapore",36),
("Balrampur",35),
("Jirapur",23),
("Serampore",36),
("Champawat",34),
("Banapura",23),
("Kolhapur",21),
("Ottapalam",17),
("Ghograpar",4),
("Chhapiheda",23),
("Bishrampur",6),
("Deoria",35),
("Pariyaram",17),
("newasa",21),
("Dighi",21),
("Davangere",18),
("Bellary",18),
("Baddi",13),
("Attur",31),
("Manipal",18),
("Bokaro",16),
("Kanpur Nagar",35),
("Eloor",17),
("Edapally",17),
("Online",0);

-- unique constraint i jsut removed on mobile
CREATE TABLE patients (
	patient_id int PRIMARY KEY auto_increment,
    health_id VARCHAR(255) null,
    patient_name VARCHAR(255) not null,
    gender CHAR(1) not null,
    dob DATE not null,
    mobile VARCHAR(15) not null,
    occupation VARCHAR(255),
    state INT not null,
	FOREIGN KEY (state) REFERENCES states(state_id),
	city INT not null,
	FOREIGN KEY (city) REFERENCES cities(city_id),
    pincode VARCHAR(10) not null,
    visit_type INT,
    FOREIGN KEY (visit_type) REFERENCES visit_type(visit_type_id),
    created_by INT null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE patient_doctor_relation(
	patient_doctor_relation_id int PRIMARY KEY auto_increment,
	user_map_id INT not null,
    patient_id INT not null,
	FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    visit_type INT,
    FOREIGN KEY (visit_type) REFERENCES visit_type(visit_type_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE patient_diagnostic_report(
	id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
	FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
	report_type varchar(200),
    report_category varchar(200),
    laboratory_test_name varchar(200), 
    report_conclusion varchar(200),
    reporting_Doctor varchar(200),
    upload_file LONGBLOB,
    upload_file_name varchar(200),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE patient_op_consultation(
id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
	FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    notes varchar(200),
    upload_file longtext,
    upload_file_name varchar(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE patient_record_discharge_summary(
    id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
	FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    notes varchar(200),
    upload_file LONGBLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);   


CREATE TABLE patient_record_prescription(
    id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
	FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    notes varchar(200),
    upload_file LONGBLOB,
    upload_file_name varchar(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);