create DATABASE hims;
use hims;
CREATE TABLE visit_type(
    visit_type_id INT PRIMARY KEY auto_increment,
    visit_type VARCHAR(255) not null
);
insert into visit_type
values (1, "Out Patient"),
    (2, "In Patient"),
    (3, "Emergency"),
    (4, "Day Care");
    
CREATE TABLE states(
    state_id INT PRIMARY KEY auto_increment,
    state_name VARCHAR(255)
);
insert into states (state_name)
values ("ANDAMAN AND NICOBAR ISLANDS"),
    ("ANDHRA PRADESH"),
    ("ARUNACHAL PRADESH"),
    ("ASSAM"),
    ("BIHAR"),
    ("CHHATTISGARH"),
    ("CHANDIGARH"),
    ("DADRA & NAGAR HAVELI AND DAMAN & DIU"),
    ("DELHI"),
    ("LADAKH"),
    ("GOA"),
    ("GUJARAT"),
    ("HIMACHAL PRADESH"),
    ("HARYANA"),
    ("JAMMU AND KASHMIR"),
    ("JHARKHAND"),
    ("KERALA"),
    ("KARNATAKA"),
    ("LAKSHADWEEP"),
    ("MEGHALAYA"),
    ("MAHARASHTRA"),
    ("MANIPUR"),
    ("MADHYA PRADESH"),
    ("MIZORAM"),
    ("NAGALAND"),
    ("PUNJAB"),
    ("PUDUCHERRY"),
    ("RAJASTHAN"),
    ("SIKKIM"),
    ("TAMIL NADU"),
    ("TRIPURA"),
    ("TELANGANA"),
    ("UTTARAKHAND"),
    ("UTTAR PRADESH"),
    ("WEST BENGAL"),
    ("ODISHA");

CREATE TABLE cities(
    city_id INT PRIMARY KEY auto_increment,
    city_name VARCHAR(255),
    state_id INT NOT NULL
    -- FOREIGN KEY (state_id) REFERENCES states(state_id) 
);

INSERT INTO cities (city_name, state_id)
values ("Srikakulam", 2),
    ("Parvathipuram Manyam", 2),
    ("Vizianagaram", 2),
    ("Visakhapatnam", 2),
    ("Alluri Sitharama Raju", 2),
    ("Anakapalli", 2),
    ("Kakinada", 2),
    ("East Godavari", 2),
    ("Konaseema", 2),
    ("Eluru", 2),
    ("West Godavari", 2),
    ("NTR", 2),
    ("Krishna", 2),
    ("Palnadu", 2),
    ("Guntur", 2),
    ("Bapatla", 2),
    ("Prakasam", 2),
    ("Nellore", 2),
    ("Kurnool", 2),
    ("Nandyal", 2),
    ("Anantapuramu", 2),
    ("Sri Sathya Sai", 2),
    ("YSR", 2),
    ("Annamayya", 2),
    ("Tirupati", 2),
    ("Chittoor", 2),
    ("Anjaw", 3),
    ("Changlang", 3),
    ("Kamle", 3),
    ("Kra Daadi", 3),
    ("Kurung Kumey", 3),
    ("Lepa-Rada", 3),
    ("Lohit", 3),
    ("Longding", 3),
    ("Namsai", 3),
    ("Pakke-Kessang", 3),
    ("Papum Pare", 3),
    ("Shi-Yomi", 3),
    ("Siang", 3),
    ("Tawang", 3),
    ("Tirap", 3),
    ("Lower Dibang Valley", 3),
    ("Dibang Valley", 3),
    ("East Kameng", 3),
    ("West Kameng", 3),
    ("East Siang", 3),
    ("Lower Siang", 3),
    ("Upper Siang", 3),
    ("West Siang", 3),
    ("Lower Subansiri", 3),
    ("Upper Subansiri", 3),
    ("Itanagar", 3),
    ("Baksa", 4),
    ("Bajali", 4),
    ("Barpeta", 4),
    ("Biswanath", 4),
    ("Bongaigaon", 4),
    ("Cachar", 4),
    ("Charaideo", 4),
    ("Chirang", 4),
    ("Darrang", 4),
    ("Dhemaji", 4),
    ("Dhubri", 4),
    ("Dibrugarh", 4),
    ("Dima Hasao", 4),
    ("Goalpara", 4),
    ("Golaghat", 4),
    ("Hailakandi", 4),
    ("Hojai", 4),
    ("Jorhat", 4),
    ("Kamrup Metropolitan", 4),
    ("Kamrup", 4),
    ("Karbi Anglong", 4),
    ("Karimganj", 4),
    ("Kokrajhar", 4),
    ("Lakhimpur", 4),
    ("Majuli", 4),
    ("Morigaon", 4),
    ("Nagaon", 4),
    ("Nalbari", 4),
    ("Sivasagar", 4),
    ("Sonitpur", 4),
    ("South Salmara-Mankachar", 4),
    ("Tamulpur", 4),
    ("Tinsukia", 4),
    ("Udalguri", 4),
    ("West Karbi Anglong", 4),
    ("Araria", 5),
    ("Arwal", 5),
    ("Aurangabad", 5),
    ("Banka", 5),
    ("Begusarai", 5),
    ("Bhagalpur", 5),
    ("Bhojpur", 5),
    ("Buxar", 5),
    ("Darbhanga", 5),
    ("East Champaran", 5),
    ("Gaya", 5),
    ("Gopalganj", 5),
    ("Jamui", 5),
    ("Jehanabad", 5),
    ("Khagaria", 5),
    ("Kishanganj", 5),
    ("Kaimur", 5),
    ("Katihar", 5),
    ("Lakhisarai", 5),
    ("Madhubani", 5),
    ("Munger", 5),
    ("Madhepura", 5),
    ("Muzaffarpur", 5),
    ("Nalanda", 5),
    ("Nawada", 5),
    ("Patna", 5),
    ("Purnia", 5),
    ("Rohtas", 5),
    ("Saharsa", 5),
    ("Samastipur", 5),
    ("Sheohar", 5),
    ("Sheikhpura", 5),
    ("Saran", 5),
    ("Sitamarhi", 5),
    ("Supaul", 5),
    ("Siwan", 5),
    ("Vaishali", 5),
    ("West Champaran", 5),
    ("Balod", 6),
    ("Baloda Bazar", 6),
    ("Balrampur", 6),
    ("Bastar", 6),
    ("Bemetara", 6),
    ("Bijapur", 6),
    ("Bilaspur", 6),
    ("Dantewada", 6),
    ("Dhamtari", 6),
    ("Durg", 6),
    ("Gariaband", 6),
    ("Gaurella-Pendra-Marwahi", 6),
    ("Janjgir-Champa", 6),
    ("Jashpur", 6),
    ("Kabirdham", 6),
    ("Kanker", 6),
    ("Kondagaon", 6),
    ("Khairagarh-Chhuikhadan-Gandai", 6),
    ("Korba", 6),
    ("Koriya", 6),
    ("Mahasamund", 6),
    ("Manendragarh-Chirmiri-Bharatpur", 6),
    ("Mohla-Manpur-Chowki", 6),
    ("Mungeli", 6),
    ("Narayanpur", 6),
    ("Raigarh", 6),
    ("Raipur", 6),
    ("Rajnandgaon", 6),
    ("Sarangarh-Bilaigarh", 6),
    ("Sakti", 6),
    ("Sukma", 6),
    ("Surajpur", 6),
    ("Surguja", 6),
    ("North Goa", 11),
    ("South Goa", 11),
    ("Ahmedabad", 12),
    ("Amreli", 12),
    ("Anand", 12),
    ("Aravalli", 12),
    ("Banaskantha", 12),
    ("Bharuch", 12),
    ("Bhavnagar", 12),
    ("Botad", 12),
    ("Chhota Udaipur", 12),
    ("Dahod", 12),
    ("Dang", 12),
    ("Devbhoomi Dwarka", 12),
    ("Gandhinagar", 12),
    ("Gir Somnath", 12),
    ("Jamnagar", 12),
    ("Junagadh", 12),
    ("Kutch", 12),
    ("Kheda", 12),
    ("Mahisagar", 12),
    ("Mehsana", 12),
    ("Morbi", 12),
    ("Narmada", 12),
    ("Navsari", 12),
    ("Patan", 12),
    ("Porbandar", 12),
    ("Rajkot", 12),
    ("Sabarkantha", 12),
    ("Surat", 12),
    ("Surendranagar", 12),
    ("Tapi", 12),
    ("Vadodara", 12),
    ("Valsad", 12),
    ("Panchmahal", 12),
    ("Ambala", 14),
    ("Bhiwani", 14),
    ("Charkhi Dadri", 14),
    ("Faridabad", 14),
    ("Fatehabad", 14),
    ("Gurugram", 14),
    ("Hisar", 14),
    ("Jhajjar", 14),
    ("Jind", 14),
    ("Kaithal", 14),
    ("Karnal", 14),
    ("Kurukshetra", 14),
    ("Mahendragarh", 14),
    ("Nuh", 14),
    ("Palwal", 14),
    ("Panchkula", 14),
    ("Panipat", 14),
    ("Rewari", 14),
    ("Rohtak", 14),
    ("Sirsa", 14),
    ("Sonipat", 14),
    ("Yamunanagar", 14),
    ("Bilaspur", 13),
    ("Chamba", 13),
    ("Hamirpur", 13),
    ("Kangra", 13),
    ("Kinnaur", 13),
    ("Kullu", 13),
    ("Lahaul and Spiti", 13),
    ("Mandi", 13),
    ("Shimla", 13),
    ("Sirmaur", 13),
    ("Solan", 13),
    ("Una", 13),
    ("Bokaro", 16),
    ("Chatra", 16),
    ("Deoghar", 16),
    ("Dhanbad", 16),
    ("Dumka", 16),
    ("East Singhbhum", 16),
    ("Garhwa", 16),
    ("Giridih", 16),
    ("Godda", 16),
    ("Gumla", 16),
    ("Hazaribagh", 16),
    ("Jamtara", 16),
    ("Khunti", 16),
    ("Kodarma", 16),
    ("Latehar", 16),
    ("Lohardaga", 16),
    ("Pakur", 16),
    ("Palamu", 16),
    ("Ramgarh", 16),
    ("Ranchi", 16),
    ("Sahibganj", 16),
    ("Saraikela Kharsawan", 16),
    ("Simdega", 16),
    ("West Singhbhum", 16),
    ("Bagalkote", 18),
    ("Bengaluru Urban", 18),
    ("Bengaluru Rural", 18),
    ("Belagavi", 18),
    ("Ballary", 18),
    ("Bidar", 18),
    ("Vijayapura", 18),
    ("Chamarajanagara", 18),
    ("Chikkaballapura", 18),
    ("Chikkamagaluru", 18),
    ("Chitradurga", 18),
    ("Dakshina Kannada", 18),
    ("Davanagere", 18),
    ("Dharwad", 18),
    ("Gadag", 18),
    ("Kalaburagi", 18),
    ("Hassan", 18),
    ("Haveri", 18),
    ("Kodagu", 18),
    ("Kolara", 18),
    ("Koppala", 18),
    ("Mandya", 18),
    ("Mysuru", 18),
    ("Raichuru", 18),
    ("Ramanagara", 18),
    ("Shivamogga", 18),
    ("Tumakuru", 18),
    ("Udupi", 18),
    ("Uttara Kannada", 18),
    ("Vijayanagara", 18),
    ("Yadgiri", 18),
    ("Alappuzha", 17),
    ("Ernakulam", 17),
    ("Idukki", 17),
    ("Kannur", 17),
    ("Kasaragod", 17),
    ("Kollam", 17),
    ("Kottayam", 17),
    ("Kozhikode", 17),
    ("Malappuram", 17),
    ("Palakkad", 17),
    ("Pathanamthitta", 17),
    ("Thiruvananthapuram", 17),
    ("Thrissur", 17),
    ("Wayanad", 17),
    ("Bhopal", 23),
    ("Raisen", 23),
    ("Rajgarh", 23),
    ("Sehore", 23),
    ("Vidisha", 23),
    ("Morena", 23),
    ("Sheopur", 23),
    ("Bhind", 23),
    ("Gwalior", 23),
    ("Ashoknagar", 23),
    ("Shivpuri", 23),
    ("Datia", 23),
    ("Guna", 23),
    ("Alirajpur", 23),
    ("Barwani", 23),
    ("Burhanpur", 23),
    ("Indore", 23),
    ("Dhar", 23),
    ("Jhabua", 23),
    ("Khandwa", 23),
    ("Khargone", 23),
    ("Balaghat", 23),
    ("Chhindwara", 23),
    ("Jabalpur", 23),
    ("Katni", 23),
    ("Mandla", 23),
    ("Narsinghpur", 23),
    ("Seoni", 23),
    ("Dindori", 23),
    ("Betul", 23),
    ("Harda", 23),
    ("Narmadapuram", 23),
    ("Rewa", 23),
    ("Satna", 23),
    ("Sidhi", 23),
    ("Singrauli", 23),
    ("Chhatarpur", 23),
    ("Damoh", 23),
    ("Panna", 23),
    ("Sagar", 23),
    ("Tikamgarh", 23),
    ("Niwari", 23),
    ("Anuppur", 23),
    ("Shahdol", 23),
    ("Umaria", 23),
    ("Agar Malwa", 23),
    ("Dewas", 23),
    ("Mandsaur", 23),
    ("Neemuch", 23),
    ("Ratlam", 23),
    ("Shajapur", 23),
    ("Ujjain", 23),
    ("Sangli", 21),
    ("Satara", 21),
    ("Solapur", 21),
    ("Kolhapur", 21),
    ("Pune", 21),
    ("Akola", 21),
    ("Amravati", 21),
    ("Buldhana", 21),
    ("Yavatmal", 21),
    ("Washim", 21),
    ("Aurangabad", 21),
    ("Beed", 21),
    ("Jalna", 21),
    ("Osmanabad", 21),
    ("Nanded", 21),
    ("Latur", 21),
    ("Parbhani", 21),
    ("Hingoli", 21),
    ("Bhandara", 21),
    ("Chandrapur", 21),
    ("Gadchiroli", 21),
    ("Gondia", 21),
    ("Nagpur", 21),
    ("Wardha", 21),
    ("Dhule", 21),
    ("Jalgaon", 21),
    ("Nandurbar", 21),
    ("Nashik", 21),
    ("Ahmednagar", 21),
    ("Mumbai City", 21),
    ("Mumbai Suburban", 21),
    ("Thane", 21),
    ("Palghar", 21),
    ("Raigad", 21),
    ("Ratnagiri", 21),
    ("Sindhudurg", 21),
    ("Bishnupur", 22),
    ("Chandel", 22),
    ("Churachandpur", 22),
    ("Imphal East", 22),
    ("Imphal West", 22),
    ("Jiribam", 22),
    ("Kakching", 22),
    ("Kamjong", 22),
    ("Kangpokpi", 22),
    ("Noney", 22),
    ("Pherzawl", 22),
    ("Senapati", 22),
    ("Tamenglong", 22),
    ("Tengnoupal", 22),
    ("Thoubal", 22),
    ("Ukhrul", 22),
    ("North Garo Hills", 20),
    ("East Garo Hills", 20),
    ("South Garo Hills", 20),
    ("West Garo Hills", 20),
    ("South West Garo Hills", 20),
    ("West Jaintia Hills", 20),
    ("East Jaintia Hills", 20),
    ("East Khasi Hills", 20),
    ("West Khasi Hills", 20),
    ("South West Khasi Hills", 20),
    ("Eastern West Khasi Hills", 20),
    ("Ri-Bhoi", 20),
    ("Aizawl", 24),
    ("Champhai", 24),
    ("Hnahthial", 24),
    ("Khawzawl", 24),
    ("Kolasib", 24),
    ("Lawngtlai", 24),
    ("Lunglei", 24),
    ("Mamit", 24),
    ("Saiha", 24),
    ("Saitual", 24),
    ("Serchhip", 24),
    ("ChÃƒÂ¼moukedima", 25),
    ("Dimapur", 25),
    ("Kiphire", 25),
    ("Kohima", 25),
    ("Longleng", 25),
    ("Mokokchung", 25),
    ("Mon", 25),
    ("Niuland", 25),
    ("Noklak", 25),
    ("Peren", 25),
    ("Phek", 25),
    ("Shamator", 25),
    ("Tseminyu", 25),
    ("Tuensang", 25),
    ("Wokha", 25),
    ("Zunheboto", 25),
    ("Angul", 37),
    ("Boudh", 37),
    ("Balangir", 37),
    ("Bargarh", 37),
    ("Balasore", 37),
    ("Bhadrak", 37),
    ("Cuttack", 37),
    ("Debagarh", 37),
    ("Dhenkanal", 37),
    ("Ganjam", 37),
    ("Gajapati", 37),
    ("Jharsuguda", 37),
    ("Jajpur", 37),
    ("Jagatsinghapur", 37),
    ("Khordha", 37),
    ("Kendujhar", 37),
    ("Kalahandi", 37),
    ("Kandhamal", 37),
    ("Koraput", 37),
    ("Kendrapara", 37),
    ("Malkangiri", 37),
    ("Mayurbhanj", 37),
    ("Nabarangpur", 37),
    ("Nuapada", 37),
    ("Nayagarh", 37),
    ("Puri", 37),
    ("Rayagada", 37),
    ("Sambalpur", 37),
    ("Subarnapur", 37),
    ("Sundargarh", 37),
    ("Amritsar", 27),
    ("Barnala", 27),
    ("Bathinda", 27),
    ("Faridkot", 27),
    ("Fatehgarh Sahib", 27),
    ("Firozpur", 27),
    ("Fazilka", 27),
    ("Gurdaspur", 27),
    ("Hoshiarpur", 27),
    ("Jalandhar", 27),
    ("Kapurthala", 27),
    ("Ludhiana", 27),
    ("Malerkotla", 27),
    ("Mansa", 27),
    ("Moga", 27),
    ("Sri Muktsar Sahib", 27),
    ("Pathankot", 27),
    ("Patiala", 27),
    ("Rupnagar", 27),
    ("Sahibzada Ajit Singh Nagar", 27),
    ("Sangrur", 27),
    ("Shahid Bhagat Singh Nagar", 27),
    ("Tarn Taran", 27),
    ("Ajmer", 29),
    ("Alwar", 29),
    ("Banswara", 29),
    ("Baran", 29),
    ("Barmer", 29),
    ("Bharatpur", 29),
    ("Bhilwara", 29),
    ("Bikaner", 29),
    ("Bundi", 29),
    ("Chittorgarh", 29),
    ("Churu", 29),
    ("Dausa", 29),
    ("Dholpur", 29),
    ("Dungarpur", 29),
    ("Hanumangarh", 29),
    ("Jaipur", 29),
    ("Jaisalmer", 29),
    ("Jalore", 29),
    ("Jhalawar", 29),
    ("Jhunjhunu", 29),
    ("Jodhpur", 29),
    ("Karauli", 29),
    ("Kota", 29),
    ("Nagaur", 29),
    ("Pali", 29),
    ("Pratapgarh", 29),
    ("Rajsamand", 29),
    ("Sawai Madhopur", 29),
    ("Sikar", 29),
    ("Sirohi", 29),
    ("Sri Ganganagar", 29),
    ("Tonk", 29),
    ("Udaipur", 29),
    ("Gangtok", 30),
    ("Mangan", 30),
    ("Namchi", 30),
    ("Gyalshing", 30),
    ("Pakyong", 30),
    ("Soreng", 30),
    ("Ariyalur", 31),
    ("Chengalpattu", 31),
    ("Chennai", 31),
    ("Coimbatore", 31),
    ("Cuddalore", 31),
    ("Dharmapuri", 31),
    ("Dindigul", 31),
    ("Erode", 31),
    ("Kallakurichi", 31),
    ("Kanchipuram", 31),
    ("Kanyakumari", 31),
    ("Karur", 31),
    ("Krishnagiri", 31),
    ("Madurai", 31),
    ("Mayiladuthurai", 31),
    ("Nagapattinam", 31),
    ("Namakkal", 31),
    ("Nilgiris", 31),
    ("Perambalur", 31),
    ("Pudukkottai", 31),
    ("Ramanathapuram", 31),
    ("Ranipet", 31),
    ("Salem", 31),
    ("Sivagangai", 31),
    ("Tenkasi", 31),
    ("Thanjavur", 31),
    ("Theni", 31),
    ("Thoothukudi", 31),
    ("Tiruchirappalli", 31),
    ("Tirunelveli", 31),
    ("Tirupattur", 31),
    ("Tiruppur", 31),
    ("Tiruvallur", 31),
    ("Tiruvannamalai", 31),
    ("Tiruvarur", 31),
    ("Vellore", 31),
    ("Viluppuram", 31),
    ("Virudhunagar", 31),
    ("Adilabad", 33),
    ("Kumuram Bheem", 33),
    ("Mancherial", 33),
    ("Nirmal", 33),
    ("Nizamabad", 33),
    ("Jagitial", 33),
    ("Peddapalli", 33),
    ("Kamareddy", 33),
    ("Rajanna Sircilla", 33),
    ("Karimnagar", 33),
    ("Jayashankar", 33),
    ("Sangareddy", 33),
    ("Medak", 33),
    ("Siddipet", 33),
    ("Jangaon", 33),
    ("Hanamkonda", 33),
    ("Warangal", 33),
    ("Mulugu", 33),
    ("Bhadradri", 33),
    ("Khammam", 33),
    ("Mahabubabad", 33),
    ("Suryapet", 33),
    ("Nalgonda", 33),
    ("Yadadri", 33),
    ("MedchalÃ¢â‚¬â€œMalkajgiri", 33),
    ("Hyderabad", 33),
    ("Ranga Reddy", 33),
    ("Vikarabad", 33),
    ("Narayanpet", 33),
    ("Mahabubnagar", 33),
    ("Nagarkurnool", 33),
    ("Wanaparthy", 33),
    ("Jogulamba", 33),
    ("Dhalai", 32),
    ("Gomati", 32),
    ("Khowai", 32),
    ("Sipahijala", 32),
    ("Unakoti", 32),
    ("North Tripura", 32),
    ("South Tripura", 32),
    ("West Tripura", 32),
    ("Agra", 35),
    ("Mathura", 35),
    ("Mainpuri", 35),
    ("Firozabad", 35),
    ("Aligarh", 35),
    ("Etah", 35),
    ("Hathras", 35),
    ("Kasganj", 35),
    ("Prayagraj", 35),
    ("Fatehpur", 35),
    ("Kaushambi", 35),
    ("Pratapgarh", 35),
    ("Azamgarh", 35),
    ("Ballia", 35),
    ("Mau", 35),
    ("Bareilly", 35),
    ("Pilibhit", 35),
    ("Shahjahanpur", 35),
    ("Badaun", 35),
    ("Basti", 35),
    ("Sant Kabir Nagar", 35),
    ("Siddharthnagar", 35),
    ("Banda", 35),
    ("Chitrakoot", 35),
    ("Hamirpur", 35),
    ("Mahoba", 35),
    ("Bahraich", 35),
    ("Balarampur", 35),
    ("Gonda", 35),
    ("Shravasti", 35),
    ("Ayodhya", 35),
    ("Ambedkar Nagar", 35),
    ("Barabanki", 35),
    ("Sultanpur", 35),
    ("Amethi", 35),
    ("Deoria", 35),
    ("Gorakhpur", 35),
    ("Kushinagar", 35),
    ("Maharajganj", 35),
    ("Jalaun", 35),
    ("Jhansi", 35),
    ("Lalitpur", 35),
    ("Auraiya", 35),
    ("Etawah", 35),
    ("Farrukhabad", 35),
    ("Kannauj", 35),
    ("Kanpur Dehat", 35),
    ("Kanpur Nagar", 35),
    ("Hardoi", 35),
    ("Lakhimpur Kheri", 35),
    ("Lucknow", 35),
    ("Raebareli", 35),
    ("Sitapur", 35),
    ("Unnao", 35),
    ("Baghpat", 35),
    ("Bulandshahar", 35),
    ("Gautam Buddha Nagar", 35),
    ("Ghaziabad", 35),
    ("Meerut", 35),
    ("Hapur", 35),
    ("Mirzapur", 35),
    ("Sant Ravidas Nagar", 35),
    ("Sonbhadra", 35),
    ("Bijnor", 35),
    ("Amroha", 35),
    ("Moradabad", 35),
    ("Rampur", 35),
    ("Sambhal", 35),
    ("Muzaffarnagar", 35),
    ("Saharanpur", 35),
    ("Shamli", 35),
    ("Chandauli", 35),
    ("Ghazipur", 35),
    ("Jaunpur", 35),
    ("Varanasi", 35),
    ("Almora", 34),
    ("Bageshwar", 34),
    ("Chamoli", 34),
    ("Champawat", 34),
    ("Dehradun", 34),
    ("Haridwar", 34),
    ("Nainital", 34),
    ("Pauri Garhwal", 34),
    ("Pithoragarh", 34),
    ("Rudraprayag", 34),
    ("Tehri Garhwal", 34),
    ("Udham Singh Nagar", 34),
    ("Uttarkashi", 34),
    ("Alipurduar", 36),
    ("Bankura", 36),
    ("Paschim Bardhaman", 36),
    ("Purba Bardhaman", 36),
    ("Birbhum", 36),
    ("Cooch Behar", 36),
    ("Darjeeling", 36),
    ("Dakshin Dinajpur", 36),
    ("Hooghly", 36),
    ("Howrah", 36),
    ("Jalpaiguri", 36),
    ("Jhargram", 36),
    ("Kolkata", 36),
    ("Kalimpong", 36),
    ("Malda", 36),
    ("Paschim Medinipur", 36),
    ("Purba Medinipur", 36),
    ("Murshidabad", 36),
    ("Nadia", 36),
    ("North 24 Parganas", 36),
    ("South 24 Parganas", 36),
    ("Purulia", 36),
    ("Uttar Dinajpur", 36),
    ("Nicobar", 1),
    ("North and Middle Andaman", 1),
    ("South Andaman", 1),
    ("Chandigarh", 7),
    ("daman", 8),
    ("diu", 8),
    ("Dadra and Nagar Haveli", 8),
    ("Kathua", 15),
    ("Jammu", 15),
    ("Samba", 15),
    ("Udhampur", 15),
    ("Reasi", 15),
    ("Rajouri", 15),
    ("Poonch", 15),
    ("Doda", 15),
    ("Ramban", 15),
    ("Kishtwar", 15),
    ("Anantnag", 15),
    ("Kulgam", 15),
    ("Pulwama", 15),
    ("Shopian", 15),
    ("Budgam", 15),
    ("Srinagar", 15),
    ("Ganderbal", 15),
    ("Bandipora", 15),
    ("Baramulla", 15),
    ("Kupwara", 15),
    ("Leh", 10),
    ("kargil", 10),
    ("Lakshadweep", 19),
    ("central delhi", 9),
    ("East Delhi", 9),
    ("New Delhi", 9),
    ("North Delhi", 9),
    ("North East Delhi", 9),
    ("North West Delhi", 9),
    ("Shahdara", 9),
    ("South Delhi", 9),
    ("South East Delhi", 9),
    ("South West Delhi", 9),
    ("West Delhi", 9),
    ("Karaikal", 28),
    ("Mahe", 28),
    ("Pondicherry", 28),
    ("Yanam", 28);
-- unique constraint i jsut removed on mobile
CREATE TABLE patients (
    patient_id int PRIMARY KEY auto_increment,
    health_id VARCHAR(255) null,
    patient_name VARCHAR(255) not null,
    gender CHAR(1) not null,
    dob DATE not null,
    mobile VARCHAR(15) not null,
    occupation VARCHAR(255),
    state INT not null,
    FOREIGN KEY (state) REFERENCES states(state_id),
    city INT not null,
    FOREIGN KEY (city) REFERENCES cities(city_id),
    pincode VARCHAR(10) not null,
    visit_type INT,
    FOREIGN KEY (visit_type) REFERENCES visit_type(visit_type_id),
    created_by INT null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE patient_doctor_relation(
    patient_doctor_relation_id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    visit_type INT,
    FOREIGN KEY (visit_type) REFERENCES visit_type(visit_type_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE patient_diagnostic_report(
    id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    report_type varchar(200),
    report_category varchar(200),
    laboratory_test_name varchar(200),
    report_conclusion varchar(200),
    reporting_Doctor varchar(200),
    upload_file LONGBLOB,
    upload_file_name varchar(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE patient_op_consultation(
    id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    notes varchar(200),
    upload_file longtext,
    upload_file_name varchar(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE patient_record_discharge_summary(
    id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    notes varchar(200),
    upload_file LONGBLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE patient_record_prescription(
    id int PRIMARY KEY auto_increment,
    user_map_id INT not null,
    patient_id INT not null,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    notes varchar(200),
    upload_file LONGBLOB,
    upload_file_name varchar(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
